FROM node:22-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --silent
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/dist /app/dist
COPY package.json package-lock.json ./
RUN npm ci --production --silent
EXPOSE 8080
ENV NODE_ENV=production
CMD ["npm", "run", "preview", "--", "--port", "8080", "--host"]
