// Initial demo data — seeded once when the database is empty.

const avatarColors = ['#ec4899', '#22d3ee', '#f59e0b', '#a855f7', '#10b981', '#f43f5e'];
const avatar = (i) =>
  `data:image/svg+xml;utf8,${encodeURIComponent(
    `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'><defs><linearGradient id='g' x1='0' x2='1' y1='0' y2='1'><stop offset='0' stop-color='${avatarColors[i % 6]}'/><stop offset='1' stop-color='#1a1530'/></linearGradient></defs><rect width='64' height='64' rx='32' fill='url(%23g)'/></svg>`,
  )}`;

function ofUrl(handle) {
  const user = handle.replace(/^@/, '');
  return `https://onlyfans.com/${user}`;
}

const now = Date.now();
const dayOffset = (d) => new Date(now + d * 86400000);

export const seedCreators = [
  {
    id: 'c1',
    name: 'Aria Lux',
    handle: '@arialux',
    avatar: avatar(0),
    niche: 'Fashion & Lifestyle',
    status: 'active',
    revenueShare: 70,
    monthlyRevenue: 48230,
    monthlyGoal: 50000,
    subscribers: 12480,
    growth: 12.4,
    team: ['t1', 't2'],
    joinedAt: '2024-03-12',
    contractEndsAt: '2026-09-01',
    notes: 'Top performer. Push PPV bundles in Q4.',
    trend: [22, 28, 31, 35, 33, 41, 48],
    onlyfansUrl: ofUrl('@arialux'),
  },
  {
    id: 'c2',
    name: 'Nova Sky',
    handle: '@novasky',
    avatar: avatar(1),
    niche: 'Fitness',
    status: 'active',
    revenueShare: 65,
    monthlyRevenue: 31200,
    monthlyGoal: 35000,
    subscribers: 8920,
    growth: 8.1,
    team: ['t3'],
    joinedAt: '2024-06-01',
    contractEndsAt: '2026-06-01',
    notes: 'Strong engagement, improve renewal flow.',
    trend: [18, 21, 25, 27, 29, 30, 31],
    onlyfansUrl: ofUrl('@novasky'),
  },
  {
    id: 'c3',
    name: 'Mila Rose',
    handle: '@milarose',
    avatar: avatar(2),
    niche: 'Cosplay',
    status: 'active',
    revenueShare: 75,
    monthlyRevenue: 62450,
    monthlyGoal: 60000,
    subscribers: 18340,
    growth: 18.7,
    team: ['t1', 't4', 't2'],
    joinedAt: '2023-11-20',
    contractEndsAt: '2025-12-15',
    notes: 'Contract renewal upcoming!',
    trend: [40, 44, 48, 52, 55, 58, 62],
    onlyfansUrl: ofUrl('@milarose'),
  },
  {
    id: 'c4',
    name: 'Zoe Vex',
    handle: '@zoevex',
    avatar: avatar(3),
    niche: 'Alt / Gothic',
    status: 'active',
    revenueShare: 70,
    monthlyRevenue: 18900,
    monthlyGoal: 25000,
    subscribers: 5410,
    growth: -4.2,
    team: ['t3'],
    joinedAt: '2025-01-08',
    contractEndsAt: '2027-01-08',
    notes: 'Underperforming. Schedule strategy call.',
    trend: [24, 22, 21, 20, 19, 19, 18],
    onlyfansUrl: ofUrl('@zoevex'),
  },
  {
    id: 'c5',
    name: 'Luna Belle',
    handle: '@lunabelle',
    avatar: avatar(4),
    niche: 'Glamour',
    status: 'active',
    revenueShare: 68,
    monthlyRevenue: 27800,
    monthlyGoal: 30000,
    subscribers: 7650,
    growth: 5.6,
    team: ['t4'],
    joinedAt: '2024-09-15',
    contractEndsAt: '2026-09-15',
    notes: 'Solid growth, ready for tier expansion.',
    trend: [20, 22, 24, 25, 26, 27, 27],
    onlyfansUrl: ofUrl('@lunabelle'),
  },
  {
    id: 'c6',
    name: 'Ember Knox',
    handle: '@emberknox',
    avatar: avatar(5),
    niche: 'Gaming',
    status: 'onboarding',
    revenueShare: 70,
    monthlyRevenue: 0,
    monthlyGoal: 15000,
    subscribers: 0,
    growth: 0,
    team: ['t2'],
    joinedAt: '2026-05-20',
    contractEndsAt: '2028-05-20',
    notes: 'Launching next week. Brand kit pending.',
    trend: [0, 0, 0, 0, 0, 0, 0],
    onlyfansUrl: ofUrl('@emberknox'),
  },
];

export const seedContent = [
  {
    id: 'q1',
    creatorId: 'c1',
    title: 'Beach photoshoot — set #4',
    caption: 'Golden hour vibes ✨ neues Set ist da — schau vorbei!',
    type: 'PPV',
    status: 'pending',
    scheduledFor: dayOffset(0),
    price: 25,
    cover: 'linear-gradient(135deg,#ec4899,#f97316)',
  },
  {
    id: 'q2',
    creatorId: 'c3',
    title: 'Sailor Moon cosplay reveal',
    caption: 'Sailor Moon drop 🌙 wer war dabei?',
    type: 'Post',
    status: 'approved',
    scheduledFor: dayOffset(1),
    cover: 'linear-gradient(135deg,#a855f7,#22d3ee)',
  },
  {
    id: 'q3',
    creatorId: 'c2',
    title: 'Gym routine BTS',
    caption: 'BTS vom Gym-Set 💪',
    type: 'Video',
    status: 'pending',
    scheduledFor: dayOffset(2),
    cover: 'linear-gradient(135deg,#10b981,#22d3ee)',
  },
  {
    id: 'q4',
    creatorId: 'c5',
    title: 'Lingerie haul try-on',
    caption: '',
    type: 'PPV',
    status: 'draft',
    scheduledFor: dayOffset(3),
    price: 18,
    cover: 'linear-gradient(135deg,#f43f5e,#a855f7)',
  },
  {
    id: 'q5',
    creatorId: 'c4',
    title: 'Gothic Halloween teaser',
    caption: 'Spooky season incoming 🖤',
    type: 'Post',
    status: 'approved',
    scheduledFor: dayOffset(4),
    cover: 'linear-gradient(135deg,#6366f1,#ec4899)',
  },
  {
    id: 'q6',
    creatorId: 'c1',
    title: 'Morning routine vlog',
    caption: 'Morning routine — start your day with me ☀️',
    type: 'Video',
    status: 'scheduled',
    scheduledFor: dayOffset(0),
    cover: 'linear-gradient(135deg,#f59e0b,#ec4899)',
  },
  {
    id: 'q7',
    creatorId: 'c3',
    title: 'Discord Q&A teaser',
    caption: '',
    type: 'Story',
    status: 'draft',
    scheduledFor: dayOffset(2),
    cover: 'linear-gradient(135deg,#22d3ee,#a855f7)',
  },
  {
    id: 'q8',
    creatorId: 'c2',
    title: 'Protein-Shake recipe',
    caption: 'Mein Lieblings-Shake nach dem Workout 🥤',
    type: 'Post',
    status: 'scheduled',
    scheduledFor: dayOffset(6),
    cover: 'linear-gradient(135deg,#10b981,#f59e0b)',
  },
];